# Generated by Django 6.1 on 2026-08-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('Project', 'Project'), ('News', 'News')], max_length=50)),
                ('final_text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('image_type', models.CharField(choices=[('SCREENSHOT', 'SCREENSHOT'), ('AI_GENERATED', 'AI_GENERATED')], default='NONE', max_length=20)),
                ('image_path', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
